server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:travelsphere}?currentSchema=user_schema
    username: ${POSTGRES_USER:travelsphere}
    password: ${POSTGRES_PASSWORD:TravelSphere@2024}
  jpa:
    properties:
      hibernate:
        default_schema: user_schema
  flyway:
    schemas: user_schema
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: user-service-group
    topic:
      user-registered: ts.users.registered
      loyalty-updated: ts.users.loyalty-updated
